#!/usr/bin/env bash

function hook_script_header(){
    cat <<EOF >> $1 
# ----------------------------------------------
# PROJECT:   $TARGET_NAME
# BUILD:     $BUILD_DATE
# GENERATOR: mikrocfg
# ----------------------------------------------
EOF
}