#!/usr/bin/env bash

# fail on error
set -e

hook_deploy(){

    log_info "uploading config to $CONF_HOST"

     # default upload dir
    local UPLOAD_DIR="flash/"

    # file to upload
    local DIST_FILE="$1" 

    # DSN
    local SFTP_DSN="${SFTP_USER}@${CONF_HOST}"

    # /flash directory exists ? (not on CCR devices)
    {
        echo "cd flash"
    } | sftp -b - -i $SFTP_KEYFILE -P $SFTP_PORT -o UserKnownHostsFile=$SFTP_KNOWN_HOSTS -o StrictHostKeyChecking=no $SFTP_DSN && {
        log_info "directory /flash exists - assuming legacy RB/CRS device"
    } || {
        log_info "directory /flash doesn't exists - assuming modern CCR/CRS device"
        local UPLOAD_DIR=""
    }

    # upload files
    {
        echo "cd $UPLOAD_DIR"
        echo "put $DIST_FILE config.rsc"
    } | sftp -b - -i $SFTP_KEYFILE -P $SFTP_PORT -o UserKnownHostsFile=$SFTP_KNOWN_HOSTS -o StrictHostKeyChecking=no $SFTP_DSN && {
        log_success "files uploaded"
    } || {
        log_error "uploading failed"
        return 1
    }

    # wait a few seconds
    sleep 5

    # apply changes ?
    if [ "$2" == "apply" ]; then
        log_info "applying new configuration - system reset.."
        ssh -n -i $SFTP_KEYFILE -p $SFTP_PORT -o UserKnownHostsFile=$SFTP_KNOWN_HOSTS -o StrictHostKeyChecking=no $SFTP_DSN \
            "/system reset-configuration keep-users=yes run-after-reset=${UPLOAD_DIR}config.rsc" || {
            log_info "reboot.."
        }
    fi
}
