#!/usr/bin/env bash

# fail on error
set -e

hook_reboot(){

    # DSN
    local SFTP_DSN="${SFTP_USER}@${CONF_HOST}"

    ssh -n -i $SFTP_KEYFILE -p $SFTP_PORT -o UserKnownHostsFile=$SFTP_KNOWN_HOSTS -o StrictHostKeyChecking=no $SFTP_DSN \
        "/system reboot" || {
        log_warning "reboot"
    }
}
